<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part2/P2_Ch01_CH05_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conv layers with Filters

## Code.5-2-1 : Shapes with Filters


In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape =(N, n_H, n_W, n_C) )
conv = Conv2D(filters = n_filter, kernel_size = k_size)

Y = conv(images)

W, B = conv.get_weights()

print("input images : {}".format(images.shape))
print("W/B : {} /{}".format(W.shape, B.shape))
print("output Images: {}".format(Y.shape))

input images : (32, 28, 28, 3)
W/B : (3, 3, 3, 5) /(5,)
output Images: (32, 26, 26, 5)


## Code.5-2-2 : Computations with Filters

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform( minval = 0 , maxval = 1, 
                           shape = (N, n_H, n_W, n_C))
# Forward propagation(tensorflow)

conv = Conv2D( filters = n_filter , kernel_size = k_size)
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print(Y.shape)
print("Y(tensorflow): \n", Y)

W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1 , n_filter))
for c in range(n_filter):
  c_W = W[:,:,:,c]
  c_B = B[c]

  for h in range(n_H -k_size + 1):
    for j in range(n_W - k_size + 1):
      window = images[h:h+k_size,j:j+k_size ]
      conv = np.sum(window * c_W ) + c_B
      
      Y_man[h, j, c] = conv

print(Y_man.shape)
print('Y(Manual): \n',np.transpose(Y_man, (2, 0, 1)))



(3, 2, 2)
Y(tensorflow): 
 [[[-0.5469704  -1.4935812 ]
  [-0.06841962 -0.9036249 ]]

 [[ 0.13781334  0.49202162]
  [-0.4409072   0.36237657]]

 [[ 0.1924287   0.13010436]
  [-0.01863828  0.0033572 ]]]
(2, 2, 3)
Y(Manual): 
 [[[-0.54697037 -1.49358106]
  [-0.06841958 -0.90362489]]

 [[ 0.1378134   0.49202162]
  [-0.44090724  0.36237654]]

 [[ 0.19242865  0.13010432]
  [-0.01863823  0.00335726]]]


In [ ]:
# 차원 이해하기

import numpy as np

images = np.random.randint(low=0, high = 10, size = (2,3,4))
for c in range(4):
  print(images[:, :, c])
print("\n")

print(images.shape)
print("\n")

images = np.transpose(images, (2, 0, 1))
print("\n")
print(images.shape)
print("\n")

for c in range(4):
  print(images[c,:,:])

# 5-3 : Conv Layers with Activation Functions



## Code.5-3-1 : Conv Layers with Activation Functions

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filters = 3
k_size = 4

images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = (N, n_H, n_W, n_C))
#Forward Propagation (Tensorflow)
conv = Conv2D(filters = n_filters, kernel_size = k_size , activation = 'sigmoid')
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(), (2,0,1))
print("Y(tensorflow): \n", Y)

W, B = conv.get_weights()

#Forward Propagation (Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape = (n_H -k_size + 1, n_W - k_size + 1, n_filters))
for c in range(n_filter):
  c_W = W[:,:,:,c]
  c_B = B[c]
  for h in range(n_H - k_size + 1):
    for w in range(n_W - k_size + 1):
      window = images[h:h+k_size, w:w+k_size]
      conv = np.sum(window * c_W) + c_B
      conv = 1/(1+np.exp(-conv))

      Y_man[h, w, c]=conv
print("Y(manual): \n", np.transpose(Y_man,(2,0,1)))

Y(tensorflow): 
 [[[0.3349335  0.38311315]
  [0.38283285 0.38970357]]

 [[0.47541493 0.6062699 ]
  [0.5581051  0.5472177 ]]

 [[0.78086424 0.59490734]
  [0.6617485  0.6046622 ]]]
Y(manual): 
 [[[0.33493354 0.3831132 ]
  [0.38283281 0.38970363]]

 [[0.47541496 0.6062699 ]
  [0.55810512 0.54721774]]

 [[0.78086424 0.59490735]
  [0.66174851 0.60466219]]]
