<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part2/P2_Ch01_CH04_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4-4: Sparse Categorical Cross Entropy


## Code.4-4-1 : SCCE Calculation


In [ ]:
import tensorflow as tf

from tensorflow.keras.losses import SparseCategoricalCrossentropy

batch_size , n_class = 16, 5
predictions = tf.random.uniform(shape = (batch_size, n_class),
                                minval = 0, maxval=1,
                                dtype=tf.float32)
print("predictions : ", predictions)

# 값을 행별로 다 더한 후 벡터로 변환
pred_sum = tf.reshape(tf.reduce_sum(predictions, axis = 1), (-1,1))
print("pred_sum : ", pred_sum)
print(predictions.shape , pred_sum.shape)

# prediction 을 다 더한값이 1이 될 수 있도록 변환=> 확률로 변경
predictions = predictions/pred_sum

print("predictions2 : ", predictions)
print("pred_sum2: ",tf.reshape(tf.reduce_sum(predictions, axis = 1), (-1,1)))


labels =tf.random.uniform(shape = (batch_size, ),
                          minval = 0, maxval = n_class,
                          dtype = tf.int32)

print("labels: ",labels)

loss_object = SparseCategoricalCrossentropy()
loss = loss_object(labels, predictions)

print("loss.numpy: ",loss.numpy())

ce = 0
for label , prediction in zip(labels, predictions):
  print("shape",label.shape, prediction.shape)
  #print(label, prediction)
  ce += -tf.math.log(prediction[label])
ce /= batch_size
print( "ce: ",ce.numpy())

predictions :  tf.Tensor(
[[0.42568803 0.32714844 0.91588485 0.05151379 0.9393418 ]
 [0.1574285  0.9960433  0.79969513 0.9739343  0.72395194]
 [0.02427709 0.84835637 0.670138   0.02948737 0.49010515]
 [0.9394232  0.90196395 0.9452262  0.893072   0.68453276]
 [0.03382611 0.3966614  0.7024518  0.28857708 0.29094207]
 [0.9338347  0.9852246  0.27546763 0.97891796 0.5580362 ]
 [0.7454498  0.71737576 0.45415258 0.4636401  0.8068634 ]
 [0.45147884 0.87907887 0.9191135  0.32191002 0.77791953]
 [0.4892075  0.6956248  0.7345369  0.19673014 0.8999753 ]
 [0.6701274  0.54268897 0.40777183 0.8113576  0.29146016]
 [0.5256175  0.4269997  0.9489784  0.46959722 0.882185  ]
 [0.7588899  0.5227231  0.09287179 0.9341757  0.6080345 ]
 [0.61274314 0.8024304  0.11401749 0.74587333 0.94734967]
 [0.5799694  0.26895225 0.13650501 0.2935493  0.50907004]
 [0.68036187 0.90032864 0.91722727 0.675143   0.45681584]
 [0.0225141  0.8268155  0.6206163  0.5008825  0.86985004]], shape=(16, 5), dtype=float32)
pred_sum :  tf

## Code.4-4-2: SCCE with Model/Dataset

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy


N, n_feature = 100, 2
n_class = 5
batch_size = 16

X = tf.zeros(shape = (0, n_feature))
Y = tf.zeros(shape = (0,1), dtype = tf.int32)

for class_idx in range(n_class):
  center = tf.random.uniform(minval = -15, maxval = 15, shape = (2,))

  x1 = center[0] + tf.random.normal(shape=(N,1))
  x2 = center[1] + tf.random.normal(shape =(N,1))

  x= tf.concat((x1, x2), axis = 1)
  y= class_idx*tf.ones(shape=(N,1), dtype = tf.int32)

  X = tf.concat((X, x), axis = 0)
  Y = tf.concat((Y, y ), axis = 0)


dataset = tf.data.Dataset.from_tensor_slices((X, Y))
dataset = dataset.batch(batch_size)


model = Dense(units= n_class , activation = 'softmax')
loss_object = SparseCategoricalCrossentropy()

for x, y in dataset:
  predictions = model(x)
  print(predictions.shape, y.shape)
  loss = loss_object(y, predictions)
  print(loss.numpy())

(16, 5) (16, 1)
1.1347625
(16, 5) (16, 1)
1.1967789
(16, 5) (16, 1)
1.0487036
(16, 5) (16, 1)
1.1925272
(16, 5) (16, 1)
1.3015285
(16, 5) (16, 1)
1.1203533
(16, 5) (16, 1)
6.0102634
(16, 5) (16, 1)
7.9720635
(16, 5) (16, 1)
7.785532
(16, 5) (16, 1)
7.621608
(16, 5) (16, 1)
7.720002
(16, 5) (16, 1)
7.3854294
(16, 5) (16, 1)
6.4874597
(16, 5) (16, 1)
5.222967
(16, 5) (16, 1)
5.3369675
(16, 5) (16, 1)
5.093541
(16, 5) (16, 1)
5.0721045
(16, 5) (16, 1)
5.707243
(16, 5) (16, 1)
6.5345
(16, 5) (16, 1)
9.998117
(16, 5) (16, 1)
9.58814
(16, 5) (16, 1)
9.091463
(16, 5) (16, 1)
9.869771
(16, 5) (16, 1)
9.074441
(16, 5) (16, 1)
10.288221
(16, 5) (16, 1)
7.7045755
(16, 5) (16, 1)
7.5879765
(16, 5) (16, 1)
7.5715384
(16, 5) (16, 1)
7.649438
(16, 5) (16, 1)
7.503613
(16, 5) (16, 1)
7.6821804
(4, 5) (4, 1)
7.6203623


# 4-5 : Categorical Cross Entropy

## Code.4-5-1 :CCE Calculation


In [ ]:
import tensorflow as tf
from tensorflow.keras.losses import CategoricalCrossentropy

batchsize, n_class = 16, 5
predictions = tf.random.uniform(shape = (batch_size, n_class), 
                                minval=0, maxval=1,
                                dtype=tf.float32)
pred_sum = tf.reshape(tf.reduce_sum(predictions, axis =1), (-1,1))
predictions = predictions/pred_sum

labels = tf.random.uniform(shape=(batch_size, ), 
                           minval = 0, maxval = n_class,
                           dtype = tf.int32)
labels = tf.one_hot(labels, n_class)
print(labels)

loss_object = CategoricalCrossentropy()
loss = loss_object(labels, predictions)

print("CCE(Tensorflow): ", loss.numpy())

cce_man =tf.reduce_mean(tf.reduce_sum(-labels*tf.math.log(predictions), axis = 1))
print("CCE(Manual): ", cce_man.numpy())


tf.Tensor(
[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]], shape=(16, 5), dtype=float32)
CCE(Tensorflow):  2.3423333
CCE(Manual):  2.3423333


## Code.4-5-2: CCE with Model/Dataset

In [ ]:
import tensorflow as tf
from tensorflow.keras.losses import CategoricalCrossentropy

N, n_feature = 8, 2
n_class = 5

X = tf.zeros(shape = (0, n_feature))
Y = tf.zeros(shape=(0,), dtype = tf.int32)

for class_idx in range(n_class):
  center = tf.random.uniform(minval = -15, maxval = 15, shape = (2,))
  
  x1 = center[0] + tf.random.normal(shape=(N,1))
  x2 = center[1] + tf.random.normal(shape=(N,1))

  x = tf.concat((x1, x2), axis = 1)
  y = class_idx*tf.ones(shape=(N,), dtype=tf.int32)

  X = tf.concat((X,x), axis = 0)
  Y = tf.concat((Y,y), axis = 0)

Y = tf.one_hot(Y, depth= n_class, dtype = tf.int32)
dataset = tf.data.Dataset.from_tensor_slices((X,Y))
dataset = dataset.batch(batch_size)

model = Dense(units = n_class , activation= 'softmax')
loss_object = CategoricalCrossentropy()

for x, y in dataset:
  predictions = model(x)
  loss = loss_object(y, predictions)
  print(loss.numpy())



0.027198583
13.437323
13.907813
