<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/P2_Ch01_CH06_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6-1 : Max/Avg Pooling

## Code.6-1-1 : Max Pooling

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling1D

# L : 일차원벡터, f : 
L, f, s = 10, 2, 1

# input
x = tf.random.normal(shape=(1, L, 1))
pool_max = MaxPooling1D(pool_size =f, strides = s)
pooled_max = pool_max(x)
print('x:{}\n{}'.format(x.shape, x.numpy().flatten()))
print('pooled_max(Tensorflow): {}\n{}'.format(pooled_max.shape,
                                              pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros(L-f+1,)
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_max_man[i] =np.max(window)

print('pooled_max(Manual) : {}\n{}'.format(pooled_max_man.shape,
                                           pooled_max_man))

x:(1, 10, 1)
[ 1.2447166   1.3832101  -1.2515789  -0.4829862   0.9514296  -0.08912619
  0.00627052 -0.9235985  -0.9123558  -0.12326231]
pooled_max(Tensorflow): (1, 9, 1)
[ 1.3832101   1.3832101  -0.4829862   0.9514296   0.9514296   0.00627052
  0.00627052 -0.9123558  -0.12326231]
pooled_max(Manual) : (9,)
[ 1.38321006  1.38321006 -0.48298621  0.95142961  0.95142961  0.00627052
  0.00627052 -0.91235578 -0.12326231]


In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling1D

# L : 일차원벡터, f : 
L, f, s = 10, 2, 1

# input
x = tf.random.normal(shape=(1, L, 1))
pool_avg = AveragePooling1D(pool_size =f, strides = s)
pooled_avg = pool_avg(x)
print('x:{}\n{}'.format(x.shape, x.numpy().flatten()))
print('pooled_max(Tensorflow): {}\n{}'.format(pooled_avg.shape,
                                              pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros(L-f+1,)
for i in range(L-f+1):
  window = x[i:i+f]
  pooled_avg_man[i] =np.mean(window)

print('pooled_max(Manual) : {}\n{}'.format(pooled_avg_man.shape,
                                           pooled_avg_man))

x:(1, 10, 1)
[ 1.000637    0.84759986  0.01503213  1.7470822  -1.28448     0.28558975
 -1.2283832  -1.0623399  -1.0191483   1.7212859 ]
pooled_max(Tensorflow): (1, 9, 1)
[ 0.92411846  0.431316    0.8810572   0.23130113 -0.4994451  -0.4713967
 -1.1453615  -1.0407441   0.3510688 ]
pooled_max(Manual) : (9,)
[ 0.92411846  0.43131599  0.8810572   0.23130113 -0.49944511 -0.47139671
 -1.14536154 -1.04074407  0.35106879]


# 6-2 : 2D Max/Avg Pooling

## Code.6-2-1: 2D Max Pooling

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1,5,5,1
f, s = 2,1

x= tf.random.normal(shape =(N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size =f, strides = s )
pooled_max =pool_max(x)

print('x : {}\n{}'.format(x.shape, x.numpy().squeeze()))
print('pooled_max(Tensorflow): {}\n{}'.format(pooled_max.shape, 
                                              pooled_max.numpy().squeeze()))
x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape=(n_H-f+1, n_W -f+1))
for i in range(n_H - f+1):
  for j in range(n_W - f +1):
    window = x[i:i+f, j:j+f]
    pooled_max_man[i, j]= np.max(window)
print('pooled_max(Manual): {}\n{}'.format(pooled_max_man.shape,
                                          pooled_max_man))

x : (1, 5, 5, 1)
[[ 1.1603769  -0.8300858  -1.4952548  -0.48787087  1.193262  ]
 [ 0.89849615  0.72795683  1.1246506  -2.321891   -1.3592376 ]
 [-2.6366456  -0.6605461   3.3629277   0.11070692  0.18457706]
 [-0.5199297  -1.6319121  -0.9999058   0.63829446 -1.4728997 ]
 [-0.64863163 -1.4283165  -1.5529646   1.019174    0.35888112]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[ 1.1603769   1.1246506   1.1246506   1.193262  ]
 [ 0.89849615  3.3629277   3.3629277   0.18457706]
 [-0.5199297   3.3629277   3.3629277   0.63829446]
 [-0.5199297  -0.9999058   1.019174    1.019174  ]]
pooled_max(Manual): (4, 4)
[[ 1.16037691  1.1246506   1.1246506   1.19326198]
 [ 0.89849615  3.36292768  3.36292768  0.18457706]
 [-0.51992971  3.36292768  3.36292768  0.63829446]
 [-0.51992971 -0.99990582  1.01917398  1.01917398]]


# Code.6-2-2 : 2D Average Pooling

In [ ]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1,5,5,1
f, s = 2,1

x= tf.random.normal(shape =(N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size =f, strides = s )
pooled_avg =pool_avg(x)

print('x : {}\n{}'.format(x.shape, x.numpy().squeeze()))
print('pooled_avg(Tensorflow): {}\n{}'.format(pooled_avg.shape, 
                                              pooled_avg.numpy().squeeze()))
x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape=(n_H-f+1, n_W -f+1))
for i in range(n_H - f+1):
  for j in range(n_W - f +1):
    window = x[i:i+f, j:j+f]
    pooled_avg_man[i, j]= np.mean(window)
print('pooled_avg(Manual): {}\n{}'.format(pooled_avg_man.shape,
                                          pooled_avg_man))

x : (1, 5, 5, 1)
[[ 0.24530175 -1.2104038  -1.0850393  -0.5740698  -0.6450577 ]
 [-1.2462335   0.12407327  0.36363298 -0.5765526  -0.5624405 ]
 [-0.31247687 -0.1271624  -0.8405855  -1.2010375  -1.3926963 ]
 [ 0.13710935  1.2516989  -2.3642883   0.06136028 -1.4465034 ]
 [-0.5716074  -0.471651    1.1133924  -0.15693767  0.24213694]]
pooled_avg(Tensorflow): (1, 4, 4, 1)
[[-0.5218156  -0.45193422 -0.4680072  -0.5895301 ]
 [-0.39044988 -0.12001041 -0.5636357  -0.93318176]
 [ 0.23729223 -0.5200843  -1.0861378  -0.9947192 ]
 [ 0.08638746 -0.11771202 -0.33661833 -0.32498598]]
pooled_avg(Manual): (4, 4)
[[-0.5218156  -0.45193422 -0.46800721 -0.58953011]
 [-0.39044988 -0.12001041 -0.56363571 -0.93318176]
 [ 0.23729223 -0.52008432 -1.08613777 -0.99471921]
 [ 0.08638746 -0.11771202 -0.33661833 -0.32498598]]
