<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part2/P2_Ch01_CH02_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-2: Cascaded Dense Layers


### Code.2-2-1:Shapes of Cacaded Dense Layers

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape = (N, n_feature))

n_neurons = [3,5]
dense1 = Dense(units = n_neurons[0], activation = 'sigmoid')
dense2 = Dense(units = n_neurons[1], activation = 'sigmoid')

#forward propagation
A1 = dense1(x)
Y = dense2(A1)

#get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()


print("X: {} \n".format(x.shape) )

print("W1: {} ".format(W1.shape))
print("B1: {} ".format(B1.shape))
print("A1: {} \n ".format(A1.shape))

print("W2: {}".format(W2.shape))
print("B2: {}".format(B2.shape))
print("Y: {} \n".format(Y.shape))


X: (4, 10) 

W1: (10, 3) 
B1: (3,) 
A1: (4, 3) 
 
W2: (3, 5)
B2: (5,)
Y: (4, 5) 



### Code.2-2-2:Dense Layers with Python List

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
x = tf.random.normal(shape =(N, n_feature))
n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()
for n_neurons in n_neurons :
  dense = Dense( units = n_neurons, activation = 'relu')
  dense_layers.append(dense)
print("Input: ", x.shape)
for dense_idx, dense in enumerate(dense_layers) :
  X = dense(x)
  print("After dense layer", dense_idx +1)
  print(X.shape,"\n")

Input:  (4, 10)
After dense layer 1
(4, 10) 

After dense layer 2
(4, 20) 

After dense layer 3
(4, 30) 

After dense layer 4
(4, 40) 

After dense layer 5
(4, 50) 

After dense layer 6
(4, 60) 

After dense layer 7
(4, 70) 

After dense layer 8
(4, 80) 

After dense layer 9
(4, 90) 

After dense layer 10
(4, 100) 



### Code.2-2-3 : Output Calculations

In [ ]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape = (N, n_feature))
X_cp = tf.identity(X)


n_neurons = [3, 4, 5]

dense_layers = list()
for n_neuron in n_neurons :
  dense = Dense( units = n_neuron, activation = 'sigmoid')
  dense_layers.append(dense)

#forward propagation(Tensorflow)
print("Input: ", X.shape)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers) :
  X =dense(X)
  w, b = dense.get_weights()

  W.append(w)
  B.append(b)

  print("Y(tensorflow) \n", X.numpy())

#forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]

  X_cp = matmul(X_cp,w) + b
  X_cp = 1/(1 + exp(-X_cp))
  print("Y(manual): \n", X_cp.numpy())



Input:  (4, 10)
Y(tensorflow) 
 [[0.4318757  0.45237178 0.16207325]
 [0.33129793 0.355505   0.69799554]
 [0.7023533  0.25017393 0.45995662]
 [0.47758284 0.35418278 0.3156275 ]]
Y(tensorflow) 
 [[0.43893898 0.4899411  0.49027544 0.54574066]
 [0.51935667 0.41711038 0.36297423 0.57576334]
 [0.5202905  0.38122913 0.49888617 0.5584909 ]
 [0.4774691  0.44714716 0.4758805  0.5512567 ]]
Y(tensorflow) 
 [[0.34144044 0.56210375 0.42328015 0.32073724 0.4407696 ]
 [0.3620931  0.5634023  0.41613314 0.34190756 0.4352514 ]
 [0.353517   0.5878055  0.4287543  0.33788466 0.4240204 ]
 [0.34781915 0.5703563  0.4234515  0.32903472 0.43526754]]
Y(manual): 
 [[0.43187568 0.45237175 0.16207324]
 [0.3312979  0.355505   0.6979956 ]
 [0.7023533  0.25017393 0.45995662]
 [0.47758284 0.35418278 0.31562746]]
Y(manual): 
 [[0.438939   0.48994112 0.49027544 0.54574066]
 [0.51935667 0.41711038 0.36297423 0.57576334]
 [0.52029055 0.3812291  0.4988862  0.5584909 ]
 [0.47746906 0.44714716 0.47588047 0.5512567 ]]
Y(manual)

1