<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part2/P2_Ch01_CH02_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-1 : Dense Layers

### Code.2-1-1 : Shape of Dense Layers

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8,10
X = tf.random.normal(shape =(N, n_feature))

n_neuron = 3
dense = Dense(units = n_neuron, activation = 'sigmoid')
Y = dense(X)

W, B = dense.get_weights()
print('======Input/Weight/Bias =====')
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)

print(W)

======Input/Weight/Bias =====
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)
[[ 0.43057764  0.43038118 -0.5141029 ]
 [-0.1886935  -0.40849045 -0.4332217 ]
 [ 0.5033561   0.512568   -0.05504835]
 [-0.53312033  0.5127907   0.28308487]
 [-0.00306326 -0.61872643 -0.5688102 ]
 [ 0.6455296  -0.2657657  -0.55373114]
 [-0.2278749   0.67445457  0.34014523]
 [-0.5730899   0.17390889  0.1950388 ]
 [ 0.6467581  -0.11776316 -0.45947582]
 [ 0.66679823  0.44726396 -0.0206908 ]]


In [ ]:
import tensorflow as tf
import numpy as np

from tensorflow.math import exp
from tensorflow.linalg import matmul

from tensorflow.keras.layers import Dense

N, n_feature = 4,10
X = tf.random.normal(shape =(N, n_feature))

n_neuron = 3
dense = Dense(units = n_neuron, activation = 'sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()

print("Y(tensorflow):\n",Y_tf.numpy() )


#calculate with matrix multiplication 

Z = matmul(X, W) + B
Y_man_matmul = 1/(1+exp(-Z))
print("Y(manual): \n", Y_man_matmul.numpy())

#calculate with dot product
Y_man_vec = np.zeros(shape=(N, n_neuron))
for x_idx in range(N):
  x = X[x_idx]
  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx]

    z= tf.reduce_sum(x * w) + b
    a= 1/(1+np.exp(-z))
    Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot product: \n", Y_man_vec)

Y(tensorflow):
 [[0.5338247  0.14816746 0.329203  ]
 [0.24188402 0.63696253 0.6066241 ]
 [0.2865253  0.10830587 0.40427065]
 [0.3568046  0.18680632 0.47813213]]
Y(manual): 
 [[0.5338247  0.14816748 0.329203  ]
 [0.24188401 0.63696253 0.6066241 ]
 [0.2865253  0.10830589 0.40427062]
 [0.3568046  0.18680632 0.47813213]]
Y(with dot product: 
 [[0.53382473 0.1481675  0.32920298]
 [0.24188402 0.63696248 0.60662415]
 [0.28652528 0.10830587 0.40427064]
 [0.35680464 0.1868063  0.47813209]]
