<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part2/P2_Ch01_CH06_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 6-3 : 3D Max/Avg Pooling

## Code.6-3-1 : 3D Max Pooling

In [ ]:
import math
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1,5,5,3
f, s = 2,2
x=tf.random.normal(shape = (N, n_H, n_W, n_C ))
# print('x:{}\n{}'.format(x.shape,
                        # np.transpose(x.numpy().squeeze(), (2,0,1))))
pool_max = MaxPooling2D(pool_size = f, strides = s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2,0,1))

print('pooled_max(Tensorflow): {}\n{}'.format(pooled_max.shape,
                                              pooled_max_t))

###
x = x.numpy().squeeze()
n_H_ = math.floor((n_H-f)/s + 1)
n_W_ = math.floor((n_W-f)/s + 1)
print(n_H_, n_W_)
pooled_max_man = np.zeros(shape=(n_H_, n_W_, n_C))
print(pooled_max_man.shape)

for c in range(n_C):
  c_image = x[:,:,c]
   
  h_ = 0
  for h in range(0, n_H - f + 1 , s):
    w_ = 0
    for w in range(0, n_W -f + 1, s):
      window = c_image[h:h+f, w:w+f]
      pooled_max_man[h_,w_,c] =np.max(window)

      w_ +=1
    h_ +=1
pooled_max_t = np.transpose(pooled_max_man.squeeze(), (2,0,1) )
print('pooled_max(Man): {}\n{}'.format(pooled_max_man.shape,
                                       pooled_max_t           ))

pooled_max(Tensorflow): (1, 2, 2, 3)
[[[ 1.1769856  -0.68595666]
  [ 0.8137589   1.3162631 ]]

 [[ 1.1235462   0.8068078 ]
  [ 1.8374122   0.42543724]]

 [[ 0.7435361   0.85628957]
  [ 0.38841173  2.7729657 ]]]
2 2
(2, 2, 3)
pooled_max(Man): (2, 2, 3)
[[[ 1.17698562 -0.68595666]
  [ 0.81375891  1.31626308]]

 [[ 1.12354624  0.80680782]
  [ 1.83741224  0.42543724]]

 [[ 0.74353611  0.85628957]
  [ 0.38841173  2.77296567]]]


# 6-4 : Padding

## Code.6-4-1: ZeroPadding2D Layer

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape = (1,28,28,3))
print(images.shape)
# print(np.transpose(images.numpy().squeeze(), (2,0,1)))

zero_padding = ZeroPadding2D(padding =2)
y = zero_padding(images)
print(y.shape)
# print(np.transpose(y.numpy().squeeze(), (2,0,1)))


(1, 28, 28, 3)
(1, 32, 32, 3)


## Code.6-4-2 : Zero Padding with Conv2D Layers

In [ ]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1,28,28,3))

# padding = 'valid'이면 padding사용 안함, 'same'이면 input과 같은 사이즈로 알아서 패딩 생성 
conv = Conv2D(filters = 1, kernel_size = 3, padding = 'same') # f-1/2 =p = 3-1/2=1 이면 output의 shape가 input과 같음
y = conv(images)
print(y.shape)

(1, 28, 28, 1)


# 6-5 : Strides

## Code.6-5-1 : Strides in Conv2D Layers

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1,28,28,3))
conv = Conv2D(filters = 1, kernel_size = 3, padding = 'valid', strides = 2)
y = conv(images)
print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 1)


## Code.6-5-2 : Strides in Pooling Layers

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape = (1,28,28,3))
pool = MaxPooling2D(pool_size = 3, strides = 2)
y = pool(images)
print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)
