<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part2/P2_Ch01_CH05_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Convolution Layers

## Code.5-1-1 : Shapes of Conv Layers

In [7]:
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 5

# 뉴런 수 라고 생각하자
n_filter = 10

# 윈도우 사이즈( 높이 길이)
k_size = 3

images = tf.random.uniform(minval =0, maxval = 1, 
                           shape =((N, n_H, n_W, n_C)))
#print(images.shape)


conv = Conv2D(filters = n_filter, kernel_size = k_size )

y = conv(images)
W, B = conv.get_weights()

print(images.shape)
print(W.shape)
print(B.shape)
# nH - k + 1 = 26
print(y.shape)

(32, 28, 28, 5)
(3, 3, 5, 10)
(10,)
(32, 26, 26, 10)


## Code.5-1-2 : Correlation Caculation

In [26]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 1
n_filter = 1
k_size = 3
images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print("Y(tensorflow) : ", y.numpy().squeeze().shape,"\n", y.numpy().squeeze())
W, B = conv.get_weights()

###
images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)
print(B.shape)


#####
y_man = np.zeros(shape = (n_H - k_size +1, n_W - k_size + 1))
for i in range( n_H - k_size +1):
  for j in range( n_W - k_size + 1):
    #print(i, j)
    window = images[i : i + k_size, j : j + k_size]
    #print(window.shape)
    y_man[i, j] = np.sum(window * W) + B

print("Y(manual) : ", y_man.shape, "\n",y_man)

Y(tensorflow) :  (3, 3) 
 [[0.39430222 0.2896306  0.43493447]
 [0.89637583 0.7738222  0.5114556 ]
 [0.5721087  0.42440712 0.10699773]]
(5, 5)
(3, 3)
(1,)
Y(manual) :  (3, 3) 
 [[0.39430222 0.28963056 0.43493447]
 [0.89637589 0.77382207 0.5114556 ]
 [0.57210869 0.42440712 0.10699771]]


## Code.5-1-3 : Correlation with n-channel

In [30]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
k_size = 3
images = tf.random.uniform(minval = 0, maxval = 1, 
                           shape = ((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = k_size)

y = conv(images)
print("Y(tensorflow) : ", y.numpy().squeeze().shape,"\n", y.numpy().squeeze())
W, B = conv.get_weights()

###
images = images.numpy().squeeze()
W = W.squeeze()

print(images.shape)
print(W.shape)
print(B.shape)


#####
y_man = np.zeros(shape = (n_H - k_size +1, n_W - k_size + 1))
for i in range( n_H - k_size +1):
  for j in range( n_W - k_size + 1):
    #print(i, j)
    window = images[i : i + k_size, j : j + k_size, :]
    #print(window.shape)
    y_man[i, j] = np.sum(window * W) + B

print("Y(manual) : ", y_man.shape, "\n",y_man)

Y(tensorflow) :  (3, 3) 
 [[ 0.0215397   0.04528335  0.02177662]
 [ 0.6253578  -0.23627193  0.12369653]
 [ 0.42530233 -0.07219229 -0.2239751 ]]
(5, 5, 3)
(3, 3, 3)
(1,)
Y(manual) :  (3, 3) 
 [[ 0.02153972  0.04528343  0.02177659]
 [ 0.62535787 -0.23627193  0.12369654]
 [ 0.42530227 -0.07219226 -0.22397511]]
