<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part2/P2_CH01_03%2C04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1-1 : Affine Functions with 1 Feature


### Code.1-1-1 : Affine Function



In [ ]:
#1-1-1 : Affine Function

import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) #input setting (Note : input ->matrix)
print(x)
dense = Dense(units =1, activation='linear') #imp. an affine fcn

y_tf = dense(x) #forward propagation + params initialization
print(y_tf) #output

W, B = dense.get_weights()
print(W,B)

y_man = tf.linalg.matmul(x, W) + B  #forward propagation(manual)

#print results
print('=======Input/weights/Bias=========')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))


#print output
print('=======Output=======')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tf.Tensor([[3.981899]], shape=(1, 1), dtype=float32)
[[0.3981899]] [0.]
=======Input/weights/Bias=========
x: (1, 1)
[[10.]]

W: (1, 1)
[[0.3981899]]

B: (1,)
[0.]

=======Output=======
y(Tensorflow): (1, 1)
[[3.981899]]

y(Manual): (1, 1)
[[3.981899]]



### Code.1-1-1 : Params Initialization

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
#랜덤한값이 아니고 내가원하는값으로 initialize
from tensorflow.keras.initializers import Constant 

x = tf.constant([[10.]]) #input setting (Note : input ->matrix)


#weight / bias set
w, b = tf.constant(10.), tf.constant(20.)
w_init, b_init = Constant(w), Constant(b)

print(w_init, b_init)

#imp. an affine fcn
dense = Dense(units=1,
              activation= 'linear', 
              kernel_initializer = w_init,
              bias_initializer = b_init)

y_tf = dense(x)
print(y_tf)
W, B = dense.get_weights()

#print result
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))



<keras.initializers.initializers_v2.Constant object at 0x7fdc85a41f50> <keras.initializers.initializers_v2.Constant object at 0x7fdc85abeb50>
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
[[10.]]

B: (1,)
[20.]

=======Input/weights/Bias=========
x: (1, 1)
[[10.]]

W: (1, 1)
[[10.]]

B: (1,)
[20.]

=======Output=======
y(Tensorflow): (1, 1)
[[120.]]

y(Manual): (1, 1)
[[3.981899]]



# 1-2 : Affine Functions with n Features

### Code.1-2-1:Affine Functions with n Features


In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.uniform(shape = (1,10) ,minval = 0,maxval= 10 )
print(x.shape, '\n', x)

dense = Dense(units = 1)

y_tf = dense(x)  # x가 dense를 통과할때 알아서 초기화됨->몇개의 w와 b를 만들지 알아서 정함

W, B = dense.get_weights()

y_man = tf.linalg.matmul(x,W) + B  # z = xT * w +b

#print results
print('=======Input/weights/Bias=========')
print("x: {}\n{}\n".format(x.shape, x.numpy()))
print("W: {}\n{}\n".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))


#print output
print('=======Output=======')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))


(1, 10) 
 tf.Tensor(
[[5.073844   2.7787483  2.8729224  5.251088   6.6625595  4.8085475
  9.028453   0.05356669 8.296251   4.915235  ]], shape=(1, 10), dtype=float32)
=======Input/weights/Bias=========
x: (1, 10)
[[5.073844   2.7787483  2.8729224  5.251088   6.6625595  4.8085475
  9.028453   0.05356669 8.296251   4.915235  ]]

W: (10, 1)
[[ 0.33480865]
 [-0.7241754 ]
 [ 0.49532312]
 [ 0.22321999]
 [-0.57915473]
 [-0.35577396]
 [-0.4991715 ]
 [-0.32246575]
 [ 0.5988472 ]
 [-0.46280596]]

B: (1,)
[0.]

=======Output=======
y(Tensorflow): (1, 1)
[[-5.1184034]]

y(Manual): (1, 1)
[[-5.1184034]]



# 1-3 : Activation Functions

### Code. 1-3-1: Activation Layers

In [ ]:
import tensorflow as tf

from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1,5)) # input setting

# imp. activation fcn
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

#forward propagation(TensorFlow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)


#forward propagation(Manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x))/ (exp(x) + exp(-x))
y_relu_man = maximum(x,0)


print("x: {}\n{}".format(x.shape, x.numpy()))
print("Sigmaoid(tf): {}\n{}". format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmaoid(man): {}\n{}\n". format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(tf): {}\n{}". format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(man): {}\n{}\n". format(y_tanh_man.shape, y_tanh_man.numpy()))

print("Relu(tf): {}\n{}". format(y_relu_tf.shape, y_relu_tf.numpy()))
print("Relu(man): {}\n{}". format(y_relu_man.shape, y_relu_man.numpy()))


x: (1, 5)
[[-0.42802435  0.08828996 -0.8264757  -0.25554204  0.28516173]]
Sigmaoid(tf): (1, 5)
[[0.39459822 0.5220582  0.3043908  0.4364599  0.5708112 ]]
Sigmaoid(man): (1, 5)
[[0.3945982 0.5220581 0.3043908 0.4364599 0.5708113]]

Tanh(tf): (1, 5)
[[-0.40366885  0.08806126 -0.67857903 -0.25012112  0.2776756 ]]
Tanh(man): (1, 5)
[[-0.4036689   0.08806127 -0.6785791  -0.25012118  0.27767563]]

Relu(tf): (1, 5)
[[0.         0.08828996 0.         0.         0.28516173]]
Relu(man): (1, 5)
[[0.         0.08828996 0.         0.         0.28516173]]


### Code. 1-3-2: Activation in Dense Layer


In [ ]:
import tensorflow as tf
from tensorflow.math import exp, maximum

from tensorflow.keras.layers import Dense

x = tf.random.normal(shape = (1, 5)) # input setting

# imp. artificial neurons
dense_sigmoid = Dense(units= 1, activation='sigmoid' )
dense_tanh = Dense(units= 1, activation='tanh' )
dense_relu = Dense(units= 1, activation='relu' )

#forward propagation(TF)
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print("AN with Sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("AN with Tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))
print("AN with Relu: {}\n{}".format(y_relu.shape, y_relu.numpy()))


#forward propagation(Manual)
print("\n============\n")

W, b = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + b
a = 1 / ( 1 + exp(-z))
print('Activation value(TF): {}\n{}'.format(y_sigmoid.shape, y_sigmoid.numpy()))
print('Activation value(Manual): {}\n{}'.format(a.shape, a.numpy()))



AN with Sigmoid: (1, 1)
[[0.51622814]]
AN with Tanh: (1, 1)
[[0.85200435]]
AN with Relu: (1, 1)
[[0.880366]]


Activation value(TF): (1, 1)
[[0.51622814]]
Activation value(Manual): (1, 1)
[[0.51622814]]


# 1-4 : Artificial Neurons

### Code. 1-4-1: Artificial Neurons

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'
# activation = 'tanh'
# activation = 'relu'

x = tf.random.uniform( shape =(1,10))

dense = Dense(units = 1, activation = activation)
y_tf = dense(x)
W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
  y_man = 1 / ( 1 + exp(-y_man))
elif activation == 'tanh':
  y_man = (exp(y_man) - exp(y_man)) / (exp(y_man) + exp(y_man))
elif activation == 'relu':
  y_man = maximum(y_man, 0)

print("Activation :", activation)
print("y_tf: {}\n{}\n".format(y_tf.shape, y_tf))
print("y_man: {}\n{}\n".format(y_man.shape, y_man))


Activation : sigmoid
y_tf: (1, 1)
[[0.36177117]]

y_man: (1, 1)
[[0.36177117]]

