<a href="https://colab.research.google.com/github/joony0512/Deep_Learning_Class/blob/main/Part3/P3_Ch02_CH02_02%2C03%2C04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## Numpy ndarray


In [1]:
import numpy as np
a = np.array([1,2,3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


### list 와 비교

In [12]:
L = [1,2,3]
A = np.array(L)
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [3]:
for item in L:
  print(item)

1
2
3


In [4]:
for item in A:
  print(item)

1
2
3


In [5]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [6]:
A.append(4)
print(A)

AttributeError: ignored

In [13]:
A = np.append(A,4)
print(A)

[1 2 3 4]


In [8]:
L = L + [5]
print(L)

[1, 2, 3, 4, 5]


In [15]:
A = A + np.array([5])
print(A)

[11 12 13 14]


In [16]:
L = [1,2,3]
L2 = []
for item in L :
  L2.append(item*2)
print(L2)

[2, 4, 6]


In [17]:
A = np.array([1,2,3])
A2 = A*2
print(A2)

[2 4 6]


In [18]:
L * 2

[1, 2, 3, 1, 2, 3]

In [19]:
a = np.array([1,2,3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int64


In [20]:
b = np.array(a)
print(b)

[1 2 3]


In [21]:
b[0] =9
print(a)
print(b)

[1 2 3]
[9 2 3]


In [22]:
b = np.asarray(a)
print(b)

[1 2 3]


In [23]:
b[0] =9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [24]:
c = np.array(a)
c[0] = 1
print(a, b, c)

[9 2 3] [9 2 3] [1 2 3]


## 배열

In [31]:
a = np.zeros((3,4))
b = np.ones((3,4))
c = np.full((2,3), 6)
print(a)
print('\n')
print(b)
print('\n')
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[6 6 6]
 [6 6 6]]


In [33]:
d = np.empty((3,3))
print(d)

[[3.11125627e-316 0.00000000e+000 6.94891159e-310]
 [6.94891159e-310 6.94891159e-310 6.94891159e-310]
 [6.94891159e-310 6.94884972e-310 1.18575755e-321]]


In [35]:
e = np.zeros_like(a)
f = np.ones_like(a)
g = np.full_like(a,2)
h = np.empty_like(a)
print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3.1928514e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [37]:
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
k = np.arange(10)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
k = np.arange(1, 11)
print(k)

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
k = np.arange(10, 0, -1)
print(k)

[10  9  8  7  6  5  4  3  2  1]


In [43]:
# uniform distribution
l = np.random.rand(2,2)
print(l)

[[0.3838541  0.76648852]
 [0.68051002 0.51749511]]


In [44]:
# normal distribution
m = np.random.randn(2, 2)
print(m)

[[-0.23699233 -1.91538844]
 [ 0.23465114 -0.33437443]]


### 배열의 dtype

In [45]:
a = np.array([1,2,3])
b = np.array([1,2,3], dtype= np.float64)
c = np.array([1,2,3], dtype = np.int32)
print(a.dtype, b.dtype, c.dtype)

int64 float64 int32


In [47]:
i = np.array([1,2,3], dtype = 'f')
print(i.dtype)

float32


In [48]:
i = i.astype(np.int32)
print(i.dtype)

int32


In [49]:
j = j.astype(i.dtype)
print(j.dtype)

int32


## 배열의 인덱싱(indexing)과 슬라이싱(slicing)

In [50]:
a = np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [51]:
#indexing
print(a[5])

5


In [52]:
#slicing
print(a[0:2])

[0 1]


In [53]:
print(a[-1])

9


In [54]:
print(a[7:-1])

[7 8]


In [55]:
a[5:8] = 10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


### indexing과 slicing의 차이
인덱싱을 사용하면 항상 랭크가 감소된다, 반면에 슬라이싱을 사용하면 차원이 유지된다.

In [56]:
b= np.arange(1,13)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [57]:
indexing = b[1]
slicing = b[1:2]
print(indexing, indexing.shape, indexing.ndim)
print(slicing, slicing.shape, slicing.ndim)

2 () 0
[2] (1,) 1


In [58]:
b = b.reshape(3,4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [59]:
row_r1 = b[1,:]
row_r2 = b[1:2, :]
print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


### Slicing Example

In [63]:
c = np.arange(24).reshape(2,3,4)
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [64]:
print(c[:,:, :1])
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [66]:
print(c[0:1])
print(c[0::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


### boolean indexing

In [67]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [69]:
bool_idx = (c>10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [70]:
print(c[bool_idx])

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [71]:
c[c>10] = -1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


### fancy indexing

In [74]:
d = np.arange(8).reshape(8,-1) # -1자리에 뭐가들어갈지 알아서 계산해줌
e = np.arange(16).reshape(8, -1)
print(d, d.shape)
print(e, e.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]] (8, 2)


In [75]:
d = np.hstack((d, d, d, d))
print(d, d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [78]:
print(d[[3,5,1,0]])

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [79]:
print(d[[-3,-5,-7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [83]:
e = np.arange(32).reshape(8,-1)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [85]:
print(e[[1,5,7,2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [84]:
print(e[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]


In [87]:
print(e[[1,5,7,2]][...,[0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


## Transepose

In [88]:
f = np.arange(16).reshape(2,2,4)
print(f,f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [89]:
print(f.transpose(1,0,2)) #0번축과 1번축 바꾸기

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [91]:
print(f.swapaxes(0,1))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [94]:
print(f.transpose(2,1,0).shape)
# 파이토치와 텐서플로우의 이미지shape맞출때 많이 사용한다

(4, 2, 2)


## Numpy 연산

In [95]:
x = np.array([[1,2],[3,4]], dtype = np.float64)
y = np.array([[5,6],[7,8]], dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [96]:
print(x + y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [97]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [98]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [100]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [102]:
print(x@y)
print(np.matmul(x,y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [103]:
z = np.arange(1,11).reshape(2,-1)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [104]:
print(np.sum(z))

55


### 축의 의미
axis = 0 --> 0번째 축의 값을 바꿔가면서 연산해라  
axis = 1 --> 1번째 축의 값을 바꿔가면서 연산해라  
axis = -1 --> 마지막 축의 값을 바꿔가면서 연산해라

In [106]:
sum1 = np.sum(z, axis = 0)
sum2 = np.sum(z, axis = 1)
print(sum1, sum2)

[ 7  9 11 13 15] [15 40]


In [108]:
sum3 = np.sum(z, axis = -1)
print(sum3)

[15 40]


In [109]:
#axis = 0
print(z[0,:]+z[1,:])


[ 7  9 11 13 15]


In [110]:
#axis = 1
print(z[:, 0]+z[:,1]+z[:,2]+z[:,3])

[10 30]


## Broadcasting

In [111]:
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y = np.array([1,0,2])

In [112]:
print(x,x.shape)
print(y,y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)
[1 0 2] (3,)


In [114]:
z = x+y
print(z, z.shape)
# 모든 행에 더해짐 : 알아서 차원을 (4,3)으로 늘려서 더한것 : Broadcasting

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크쪽에 1을 붙입니다.  
2. 두 배열은 차원에서 크기가 같거나 배열 중 하나의 차원에 크기가 1인 경우 차원에서 호환가능하다고 합니다.
3. 배열은 모든 차원에서 호환되면 함께 broadcast할 수 있습니다.
4. Broadcast한 후 각 배열은 두개의 입력배열의 요소 모양 최대 개수와 동일한 모양을 가진것 처럼 동작합니다.
5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫번째 배열은 마치 해당차원을 따라 복사된 것 처럼 작동합니다  
  
예 :  shape의 변화  

(5,3) + (3,)  
(5,3) + (1,3)  
(5,3) + (5,3)  
(5,3)

In [115]:
x = np.array([1,2,3]).reshape(1,3)
y = np.array([4,5]).reshape(1,2)
print(x, x.shape)
print(y, y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [116]:
print(x+y)

ValueError: ignored

In [118]:
y = y.swapaxes(0,1)
print(y, y.shape)

[[4]
 [5]] (2, 1)


In [119]:
#Broadcasting 발생
print(x + y)

[[5 6 7]
 [6 7 8]]


## Shape 변경

In [120]:
a = np.arange(24).reshape(2,3,4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [121]:
a = a.reshape(4, -1)
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [122]:
a = a[... , np.newaxis]
print(a.shape)

(4, 6, 1)


In [130]:
a = a.reshape(4,6)
a = np.expand_dims(a,axis = -1) # 맨 위 차원 확장
print(a,a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [139]:
a = a.reshape(4,6)
a = np.expand_dims(a,axis = 0) 
print(a,a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [144]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [145]:
c = np.concatenate((a,b), axis = -1)
print(c, c.shape)

[[[ 0  1  2  3  4  5  0  1  2  3  4  5]
  [ 6  7  8  9 10 11  6  7  8  9 10 11]
  [12 13 14 15 16 17 12 13 14 15 16 17]
  [18 19 20 21 22 23 18 19 20 21 22 23]]] (1, 4, 12)


In [146]:
c = np.concatenate((a,b), axis = 0)
print(c, c.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (2, 4, 6)


In [147]:
c = np.concatenate((a,b), axis = 1)
print(c, c.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 8, 6)


In [148]:
d = np.stack((a,b), axis = -1)
print(d, d.shape)


[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]

  [[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]

  [[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]

  [[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (1, 4, 6, 2)


In [149]:
d = np.stack((a,b), axis = 0)
print(d, d.shape)


[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]] (2, 1, 4, 6)
